<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>TestUnit</RootNamespace>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MeCab.DotNet" Version="1.2.0" />
    <PackageReference Include="MSTest" Version="4.0.2" />
    <PackageReference Include="jieba.NET" Version="0.42.2" GeneratePathProperty="True" />
  </ItemGroup>

  <ItemGroup>
    <None Include="$(Pkgjieba_NET)\Resources\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Resources\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\filereader-mcp-server\filereader-mcp-server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
