<#
.SYNOPSIS
 Generate markdown documentation for the FileReader MCP server's tools.
#>


# Ensure UTF8 encoding for Windows environment
[Console]::InputEncoding = [System.Text.Encoding]::UTF8
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

$ProjectRoot = Join-Path $PSScriptRoot "..\src\FileReaderMcpServer"
$McpServerExe = Join-Path $ProjectRoot "bin\Debug\net10.0\filereader-mcp-server.exe"

# Build if necessary
dotnet build -c Debug $(Join-Path $ProjectRoot "FileReaderMcpServer.csproj") | Out-Null

$psi = New-Object System.Diagnostics.ProcessStartInfo
$psi.FileName = $McpServerExe
$psi.Arguments = "`"$PWD`""
$psi.UseShellExecute = $false
$psi.RedirectStandardInput = $true
$psi.RedirectStandardOutput = $true
$psi.RedirectStandardError = $true
$psi.StandardOutputEncoding = [System.Text.Encoding]::UTF8
$proc = [System.Diagnostics.Process]::Start($psi)

$request = '{"jsonrpc":"2.0","id":1,"method":"tools/list"}'
$proc.StandardInput.WriteLine($request)

# Read the first line of output (assuming it's the JSON-RPC response)
$result = $proc.StandardOutput.ReadLine()
$proc.Kill()
$proc.Dispose()

if (-not $result) {
    Write-Error "Failed to get response from MCP server."
    exit 1
}

$data = $result | ConvertFrom-Json
$tools = $data.result.tools | Sort-Object -Property name

$md = @()
$md += "# Tools"
$md += "> Generated by [list-tools.ps1](scripts/list-tools.ps1)"
$md += ""
$md += "There are $($tools.Count) available tools provided by the FileReader MCP server."
$md += ""

foreach ($tool in $tools) {
    $md += "## $($tool.name)"
    # Preserve newlines in tool description by splitting and adding as separate lines if needed, 
    # or just let the join handle it. 
    $toolDesc = $tool.description -split "\r?\n"
    foreach ($line in $toolDesc) {
        $md += $line
    }
    $md += ""
    $md += "### Parameters"
    $md += ""
    $md += "| Name | Type | Required | Default | Description |"
    $md += "| :--- | :--- | :--- | :--- | :--- |"
    
    $props = $tool.inputSchema.properties
    $required = $tool.inputSchema.required
    if ($null -eq $props -or $($props.PSObject.Properties | Measure-Object).Count -eq 0) {
        $md += "| (none) | | | | |"
    }
    else {
        foreach ($propName in $props.PSObject.Properties.Name) {
            $prop = $props.$propName
            $type = $prop.type
            if ($type -is [array]) {
                # Handle cases where type can be multiple (e.g. ["string", "null"])
                $type = $type -join " / "
            }
            
            $isRequired = if ($null -ne $required -and ($required -contains $propName)) { "Yes" } else { "No" }
            $default = if ($null -ne $prop.default) { "``$($prop.default)``" } else { "-" }
            
            # Handle newlines and pipes in description for markdown table
            # Replace newlines with <br> to preserve them within the table cell
            $desc = $prop.description -replace '\|', '\|' -replace "\r?\n", "<br>"
            
            $md += "| ``$propName`` | $type | $isRequired | $default | $desc |"
        }
    }
    $md += ""
}

$markdownContent = $md -join "`r`n"

# Output to console
Write-Host $markdownContent

# Copy to clipboard
$markdownContent | Set-Clipboard
Write-Host "---"
Write-Host "Markdown content has been copied to the clipboard."