
name: Build and Release
permissions:
  packages: write
  contents: write
on:
  push:
    branches: [ "main" ]
    tags: ["v*"]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Build the application
      run: |
        dotnet publish .\src\FileReaderMcpServer\FileReaderMcpServer.csproj -c Release -r win-x64 --self-contained true -o win-x64

    # Upload the MSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: win-x64
  release:
    needs: [build]
    if: ${{ startsWith(github.ref,'refs/tags') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
      - name: Display structure of downloaded files and zip
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          ls -R
          zip -r9 filereader-mcp-server-win-x64-${TAG_NAME}.zip *
        
      - name: Create release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "false"
          CHANGELOG_FILE: "none"
          ALLOW_EMPTY_CHANGELOG: "true"
          TAG_PREFIX_REGEX: "[v]"
        with:
          args: |
            *.zip
